name: 'nightly artifacts cleanup'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }
          expire-in: 1days # Set this to 0 to delete all artifacts
