name: Manage caches and Artifacts

on: [workflow_dispatch]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      #---------------
      # initialize job
      #---------------

      #-----------------------------------------------------------------------------------------------
      # manage artifacts - see https://docs.github.com/en/rest/actions/artifacts
      #-----------------------------------------------------------------------------------------------

      - name: List Artifacts
        run: |
          curl -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ github.token }}" \
               "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/artifacts"

      - name: Delete Artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 0days # Set this to 0 to delete all artifacts

      #-----------------------------------------------------------------------------------------------
      # manage caches - see https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions
      #-----------------------------------------------------------------------------------------------
      
      - name: List Caches
        run: |
          curl -H 'Accept: application/vnd.github.v3+json' \
               -H "Authorization: token ${{ github.token }}" \
               "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/caches"

#      - name: Delete Caches
#        run: |
#          curl -X DELETE \
#               -H "Accept: application/vnd.github.v3+json" \
#               -H "Authorization: token ${{ github.token }}" \
#               "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/caches/1"
#      
#      - name: List Caches
#        run: |
#          curl -H 'Accept: application/vnd.github.v3+json' \
#               -H "Authorization: token ${{ github.token }}" \
#               "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/caches"
